### ISSUE TITLE
Modifying Facebook site

### ISSUE THREAD

**Issue by YadanarLin** [1f10210001/team-15-site#11]
make the" before and after" which is in the last part of the site more visually appealing.

**Comment by chanon-lim** [comment]
Here are things I think we can improve

- Change 3 icon image to fit the text
- .01, .02, .03 at the top are not equally arranged
- I think we can improve the second part of "Read More" too. because I don't understand the meaning of "read more" here.
![image](https://user-images.githubusercontent.com/85671768/122849713-3cff6f80-d336-11eb-9221-690b990de770.png)

**Comment by YadanarLin** [comment]
ok will work on those too. thank you for the suggestions

**Comment by YadanarLin** [comment]
what do you mean 01 02 and 03 icons are not equally arranged? 01 icon is a little higher because we are at the site location which is linked with 01 icon.

**Comment by YadanarLin** [comment]
the icon image is the facebook whatsapp and insta picture?

**Comment by chanon-lim** [comment]
> what do you mean 01 02 and 03 icons are not equally arranged? 01 icon is a little higher because we are at the site location which is linked with 01 icon.

At the 01 02 03 buttons, the button x location will change based on the number of the sentence, as we have two sentences long text "About" is higher than others. we may change it by adjusting the text or adjust some CSS to make the button bigger.
![image](https://user-images.githubusercontent.com/85671768/122890883-49072380-d36e-11eb-804d-c9e0e9975f44.png)
![image](https://user-images.githubusercontent.com/85671768/122890812-38ef4400-d36e-11eb-86de-fb31c61b80c2.png)




> the icon image is the facebook whatsapp and insta picture?

These icons! I don't know about the first one but I think the second one is the user icon and connect the world is the globe icon. 
![image](https://user-images.githubusercontent.com/85671768/122890085-933bd500-d36d-11eb-8c79-5e2844124a63.png)
We can also add LiveRail and Oculus icons at the child company section too

**Comment by YadanarLin** [comment]
oh right. I will look back at it.
